# pipeline_configuration.yml 파일 기본 구조
type: dev
plugin_ids: basic.*

# 프로젝트 경로 설정
project_name: "Remote_unreal_jh"
project_id: 1

# 필수 경로 설정
pc_id: 1
pc_name: "Primary"
publish_path: "c:/shotgrid_config/tk-config-unreal_ww"
source_control_path: "c:/shotgrid_config/tk-config-unreal_ww"